load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "stock_data_test",
    srcs = ["stock_data_test.py"],
    tags = ["requires-network"],
    deps = [
        "//bazel/python/src:stock_data",
    ],
)
