load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "stock_data",
    srcs = ["stock_data.py"],
    data = ["tracked_tickers.json"],
    visibility = ["//visibility:public"],
)
