name: C# Tests

on:
  schedule:
    - cron: 0 */6 * * *
  pull_request: {}

jobs:
  csharp_test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup .NET
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore csharp/ItsAlwaysSunnyOnEarth.sln

      - name: Build
        run: dotnet build csharp/ItsAlwaysSunnyOnEarth.sln --no-restore --configuration Release

      - name: Test
        id: run_tests
        run: dotnet test csharp/ItsAlwaysSunnyOnEarth.Tests/ItsAlwaysSunnyOnEarth.Tests.csproj --no-build --configuration Release --logger "junit;LogFilePath=test-results/csharp-junit.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
        continue-on-error: true

      - name: Process test results
        if: ${{ always() }}
        uses: trunk-io/analytics-uploader@main
        env:
          TRUNK_PUBLIC_API_ADDRESS: ${{ vars.TRUNK_API_ENDPOINT }}
        with:
          # Path to your test results.
          # This path should match the LogFilePath used in the dotnet test command.
          junit-paths: csharp/**/test-results/csharp-junit.xml
          # Provide your Trunk organization slug.
          org-slug: ${{ vars.ORG_SLUG }}
          # Provide your Trunk API token as a GitHub secret.
          token: ${{ secrets.TRUNK_TOKEN }}
          # Pass the test outcome for quarantining support
          previous-step-outcome: ${{ steps.run_tests.outcome }}
          test-collection-id: cIB9Um7C

      - name: Upload test results
        if: always() # Always run this step to upload results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: csharp-test-results
          path: csharp/**/test-results/csharp-junit.xml
