name: Rust Tests

on:
  schedule:
    - cron: 0 */6 * * *
  pull_request: {}

jobs:
  rust_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3      - uses: actions/checkout@v4      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Build
        run: cargo build -q --all --manifest-path=./rust/Cargo.toml

      - name: Install nextest
        run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - name: Install trunk-analytics-cli
        run: bash get-trunk-cli "${{ vars.ANALYTICS_CLI_PRE_RELEASE_TEST_VERSION }}"

      - name: Run rust tests
        id: run_tests
        if: ${{ always() }}
        run: cargo nextest run --profile=ci --manifest-path=./rust/Cargo.toml
        continue-on-error: true

      - name: Run rust tests and upload results
        env:
          TRUNK_PUBLIC_API_ADDRESS: ${{ vars.TRUNK_API_ENDPOINT }}
          TRUNK_API_TOKEN: ${{ secrets.TRUNK_TOKEN }}
        run: |
          ./trunk-analytics-cli test \
            --org-url-slug ${{ vars.ORG_SLUG }} \
            --test-collection-id WwoHUss3 \
            --junit-paths "rust/**/nextest/ci/*junit.xml" \
            -- cargo nextest run --profile=ci --manifest-path=./rust/Cargo.toml

      - name: Upload JUnit XML artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1        uses: actions/upload-artifact@v4        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2        uses: actions/upload-artifact@v4
        with:
          name: rust-junit-results
          path: rust/**/nextest/ci/*junit.xml
          retention-days: 7
